blank_issues_enabled: false
contact_links:
  - name: Questions / usage help
    url: https://github.com/jkeresman01/spring-initializr.nvim/discussions
    about: Ask and answer questions or discuss ideas here.
