name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install luacheck
        run: |
          sudo apt-get update
          sudo apt-get install luarocks
          sudo luarocks install luacheck

      - name: Lint
        run: luacheck lua/ --globals vim

      - name: Check naming/layout
        run: bash scripts/check-naming.sh
